#spring:
#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:mydb
#    username: sa
#    password: sa
#    driverClassName: org.h2.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: create-drop

## default connection pool
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: admin
    url: jdbc:mariadb://localhost:3306/default_db?shopping_db
    username: root
    password: admin