spring:
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: jdbc:mariadb://localhost:3306/shopping_jdbc
    username: root
    password: admin

server.port: 8081