spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: jdbc:mariadb://localhost:3306/shopping_jpa
    username: root
    password: admin